create extension if not exists vector;

create table if not exists "public"."embeddings" (
    "id" bigint generated by default as identity primary key,
    "created_at" timestamp with time zone default now(),
    "dataset" text not null,
    "document" text not null,
    "embedding_model" text not null,
    "embedding_1536" vector(1536)
);
